---
- name: Update Zypper repository and cache
  zypper:
    name: "*"
    state: latest
    update_cache: yes

- name: Perform a full system upgrade
  zypper:
    name: "*"
    state: latest

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot system if required
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Remove unnecessary dependencies
  zypper:
    name: "*"
    state: absent
    autoremove: yes

- name: Clean up Zypper cache
  zypper:
    name: "*"
    autoclean: yes

- name: Update GRUB bootloader
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Final system reboot after cleanup
  reboot:
    msg: "Reboot initiated by Ansible after cleanup"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
